library(tidyverse)
library(dslabs)
library(readr)
library(readxl)
library(purrr)
install.packages("htmlwidgets")
install.packages("purrr")

data("reported_heights")
setwd("C:/Users/jamesw/Documents/ds-education")